# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Y. Jin"
tagline:          "Jin Yonghao's Homepage"
description:      "The true logic of this world is the calculus of probability. --J. C. Maxwell"
url:              http://jyh1.github.io
baseurl:          /

author:
  name:           'Jin Yonghao'
  url:            https://jyh1.github.io

paginate:         5

# Custom vars
version:          1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/jyh1
